### ISSUE TITLE
US-FL data in commit f3c3796

### ISSUE THREAD

**Issue by sfbay** [amcharts/covid-charts#11]
{"confirmed":123019,"deaths":499,"recovered":0,"id":"US-FL"}

should be

{"confirmed":21019,"deaths":499,"recovered":0,"id":"US-FL"}

https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429/

**Comment by martynasma** [comment]
Not seeing the issue now with Florida. Must have been temporary data glitch.
