### ISSUE TITLE
Overall active cases count is miscalculated

### ISSUE THREAD

**Issue by shashikanth171** [amcharts/covid-charts#17]
At https://github.com/amcharts/covid-charts/blob/142ce80650f0102ba72664f1a35e4fdb3cf6f2f5/examples/dashboard/app.js#L331 and https://github.com/amcharts/covid-charts/blob/142ce80650f0102ba72664f1a35e4fdb3cf6f2f5/examples/dashboard/app.js#L1466 active cases does not exclude deaths.

**Comment by zeroin** [comment]
Fixed

**Comment by shashikanth171** [comment]
Thank you :)
