### ISSUE TITLE
Taiwan is NOT a province of China

### ISSUE THREAD

**Issue by weichih-wen** [amcharts/covid-charts#2]
Taiwan is a COUNTRY! We have our own government and we vote for our president. China government can't even allow their people to say the word "president" and you say Taiwan is a province of Taiwan?

Remember that WHO said there are NO CONFIRMED CASES IN CHINA? But on the same day, there are 20+ confirmed cases in Taiwan. That's also the proof that Taiwan is a country, not the province of China.

**Comment by rocketkim** [comment]
I believe we should fix this. Taiwan is its own country.

**Comment by su600** [comment]
Taiwan is NOT a country.
Taiwan has been part of China since ancient times, has never been an independent country.
(Github should not be politicized.)

**Comment by rocketkim** [comment]
I think it is more political to extend "One China POLICY" on a Github repo than trying to speak of a fact... Anyway, I won't continue on this thread. Good luck.

**Comment by zeroin** [comment]
Sorry, we removed the province label.
