### ISSUE TITLE
Hong Kong data is inaccurate

### ISSUE THREAD

**Issue by kamaelxiii** [amcharts/covid-charts#4]
Latest data showing stats for Hong Kong as: `{
confirmed: 0,
deaths: 0,
recovered: 0,
id: "HK"
}`

It should be: `{
confirmed: 518,
deaths: 111,
recovered: 4,
id: "HK"
}`

I'm not sure if there are other entries with erroneous data.

**Comment by martynasma** [comment]
The source data is attributing HK to China.

We'll see if we can implement so way to separate that data to introduce some granularity.

**Comment by martynasma** [comment]
Sorry, we won't be able to add HK. Technically we can separate historical values for HK and Macau numbers, but live (current day) values are all included into China :(
